# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - braedens-client(development)

on:
  push:
    branches:
      - client-dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://braedensimages.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bf79ee1871354acb8d57e38f134d6df2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_37e89a74e6ae45b9837d8641f9ce45ad }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: braedensimages.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bf79ee1871354acb8d57e38f134d6df2 }}/braedens-frontend-developement:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'braedens-client'
        slot-name: 'development'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4c6bbc06480e4ce3811c7b0ac4c0420d }}
        images: 'braedensimages.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bf79ee1871354acb8d57e38f134d6df2 }}/braedens-frontend-developement:${{ github.sha }}'